version: '3.9'

services:

  rapid_stock:
    build: docker/php
    container_name: rapid-stock
    image: jeanne/rapid_stock:1.0
    restart: always
    ports:
      - 8011:80
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www/html
    depends_on:
      - phpmyadmin
    networks:
      - reseau_rapid_stock
      
  database:
    image: mysql:8.2
    container_name: mysql_rapid_stock
    volumes:
      - volume_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jeanne
      MYSQL_DATABASE: rapid_stock
    ports:
      - 8003:3306
    networks:
      - reseau_rapid_stock

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-rapid_stock
    ports:
      - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: jeanne
      PMA_HOST: database
    networks:
      - reseau_rapid_stock
    depends_on:
      - database

volumes:
  volume_db:
networks:
  reseau_rapid_stock: